import { Bot, ChevronDown, ChevronRight, FolderGit2, MessageSquare, MessageSquarePlus, RefreshCw, Settings, ShieldCheck } from 'lucide-react'
import type { Conversation, Repository } from '../types'
export function Sidebar({repositories,active,expanded,conversations,onSelect,onToggle,onChat,onChoose,onSync,onNew}:{repositories:Repository[];active?:string;expanded?:string;conversations:Conversation[];onSelect:(id:string)=>void;onToggle:(id:string)=>void;onChat:(chat:Conversation)=>void;onChoose:()=>void;onSync:(id:string)=>void;onNew:()=>void}){
 return <aside className="flex w-[260px] shrink-0 flex-col bg-[#101010] px-2 py-3">
  <div className="mb-3 flex items-center gap-2 px-2 py-1"><div className="grid h-7 w-7 place-items-center rounded-lg bg-white text-black"><Bot size={17}/></div><h1 className="text-sm font-semibold tracking-tight">Codebase AI</h1></div>
  <button onClick={onNew} disabled={!active} className="mb-1 flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-left text-sm hover:bg-white/[.08] disabled:opacity-35"><MessageSquarePlus size={16}/> New chat</button>
  <button onClick={onChoose} className="mb-5 flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-left text-sm text-neutral-300 hover:bg-white/[.08]"><FolderGit2 size={16}/> Add project</button>
  <p className="mb-1 px-3 text-[11px] font-medium text-neutral-500">Projects</p>
  <div className="space-y-0.5 overflow-y-auto">{repositories.map(repo=><div key={repo.id}><div className={`group flex items-center rounded-lg ${active===repo.id?'bg-white/[.09]':'hover:bg-white/[.055]'}`}><button title={expanded===repo.id?'Collapse chats':'Show project chats'} onClick={()=>onToggle(repo.id)} className="ml-1.5 rounded p-1 text-neutral-500">{expanded===repo.id?<ChevronDown size={13}/>:<ChevronRight size={13}/>}</button><button onClick={()=>onSelect(repo.id)} className="min-w-0 flex-1 px-1.5 py-2 text-left"><div className="truncate text-sm text-neutral-200">{repo.name}</div></button><button title="Sync changes" onClick={()=>onSync(repo.id)} className="mr-1.5 rounded-md p-1.5 text-neutral-500 opacity-0 hover:bg-white/10 hover:text-white group-hover:opacity-100 focus:opacity-100"><RefreshCw size={13}/></button></div>{expanded===repo.id&&<div className="ml-4 mt-0.5 space-y-0.5 border-l border-neutral-800 pl-2">{active===repo.id&&conversations.length?conversations.map(chat=><button key={chat.id} onClick={()=>onChat(chat)} className="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-[13px] text-neutral-500 hover:bg-white/[.055] hover:text-neutral-200"><MessageSquare size={12} className="shrink-0"/><span className="truncate">{chat.title}</span></button>):<p className="px-2 py-2 text-xs text-neutral-600">No chats</p>}</div>}</div>)}</div>
  <div className="mt-auto px-2 pt-3"><div className="mb-2 flex items-center gap-2 text-xs text-neutral-500"><ShieldCheck size={14}/><span>Local · Private</span></div><button className="flex w-full items-center gap-2 rounded-lg px-1 py-2 text-sm text-neutral-500 hover:text-neutral-200"><Settings size={15}/> Settings</button></div>
 </aside>
}

